config/routes.rb
Rails.application.routes.draw do


root to: 'admin/admin_session#index'
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {
        sessions: 'api/v1/user/sessions',
        registrations: 'api/v1/user/registrations'
         }
      devise_for :drivers, controllers: {
        sessions: 'api/v1/driver/sessions',
        registrations: 'api/v1/driver/registrations'
         }
      resources :vehicles do
       collection do
        post :search_vehicle
        get :get_stations
        post :vehicle_details
       end
      end
      post '/get_drivers_near_to_me', to: 'commons#get_nearest_drivers'
      get '/check_user_existence/:email', to: 'commons#check_user'
      post '/offer_trip', to: 'commons#notify_cutomer_for_price'
      get '/get_drivers_offer/:user_id', to: 'commons#get_drivers_offer'
      get 'get_driver/:driver_id', to: 'commons#get_driver'
      post 'user_sign_out', to: 'commons#user_sign_out'
      post 'driver_sign_out', to: 'commons#driver_sign_out'
      post '/start_trip', to: 'commons#start_trip'
      get 'user_forgot_password/:user_id', to: 'commons#forgot_password'
      get 'driver_forgot_password/:driver_id', to: 'commons#driver_forgot_password'
      post 'get_nearest_user_driver', to: 'commons#get_nearest_user_driver'
      post 'cancel_trip', to: 'commons#cancel_trip'
      post 'stop_trip', to: 'commons#stop_trip'
      post 'resume_trip', to: 'commons#resume_trip'
      get '/get_state', to: 'state_city#get_state'
      get '/get_cities/:state', to: 'state_city#get_cities'

    end
  end
  namespace :admin do
    get '/', to: 'admin_session#index'
    post '/login', to: 'admin_session#login'
    get '/home', to: 'admin_session#home'
    delete '/session_destory', to: 'admin_session#destroy'
    get '/privacy_policy', to: 'admin_session#privacy_policy'
    resources :drivers, only: %i(edit index update)
    resources :vehicles do
      collection do
        post :vehicle_sheet
      end
    end
    resources :users, only: %i(edit index update destroy) 

  end

  #

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/admin_session_controller.rb
class Admin::AdminSessionController < ApplicationController

	def login
		admin = User.find_by(email: admin_params[:email])
		if admin.present? && admin.type == 'Admin'
			if admin.valid_password?(admin_params[:password])
				sign_in(admin)
				redirect_to admin_home_path, notice: 'Welcome Admin in Sonaac'
			else
				flash[:error] = "email or password mismatch"
    		render "index"
			end
		else
			flash[:error] = "email or password mismatch"
  		render "index"
		end	
	end

	def home;end

	def index;end

	def privacy_policy;end

	def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    flash[:success] = "logout successfully"
    yield if block_given?
    redirect_to root_path	
	end

	private
	def admin_params
		params.require(:admin).permit(:email, :password)
	end
	
end

app/helpers/admin/admin_session_helper.rb
module Admin::AdminSessionHelper
end

app/views/admin/admin_session/home.html.erb
 <div class="jumbotron">
  <div class="container text-center">
    <h1>My Portfolio</h1>      
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
	<% end %>
    <%= form_tag vehicle_sheet_admin_vehicles_path, multipart: true do %>
  		<%= file_field_tag :file %>
  		<%= submit_tag "Import" %>
		<% end %>
    <p>Some text that represents "Me"...</p>
  </div>
</div>

app/views/admin/admin_session/index.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

<h1>Log in</h1>

<%= form_for :admin, url: admin_login_path do |f|%>
  <div class="imgcontainer">
    <!-- <img src="img_avatar2.png" alt="Avatar" class="avatar"> -->
  </div>

  <div class="container">
    <label class = "margin-10"><b>Username</b></label>
    <%= f.email_field :email, class: 'form-control margin-10', placeholder: 'Enter Username' %>

    <label class = "margin-10"><b>Password</b></label>
    <%= f.password_field :password, class: 'form-control margin-10', placeholder: 'Enter Password'%>

    <%= f.submit "Log in", class: " form-control btn btn-primary margin-10" %>
  </div>

  <div class="container  margin-10" style="background-color:#f1f1f1">
    <span class="psw" >Forgot <a href="#">password?</a></span>
  </div>
<%end%>

app/views/admin/admin_session/privacy_policy.html.erb
<div id="main-content" class="container">
	<div class="content">
		<article class="post-listing post post-537 page type-page status-publish hentry" id="the-post">
			<div class="single-post-thumb">
			</div>
			<div class="post-inner">
				<h1 class="name post-title entry-title" itemprop="itemReviewed" itemscope="" itemtype="http://schema.org/Thing"><span itemprop="name">Privacy Policy</span></h1>
				<p class="post-meta"></p>
				<div class="clear"></div>
				<div class="entry">
				<div class="insert-post-ads" style="clear:both;float:left;width:100%;margin:0 0 20px 0;"></div>
					<p>Sonaac Private Limited is a registered company and owns a mobile application <strong> http://www.Sonaac.in </strong> (hereinafter referred to as “Sonaac”), We value your trust and privacy.. This Privacy Policy is in accordance with the Indian Information Technology Act, 2000 and the Information Technology (Reasonable security and procedures and sensitive personal data or information) Rules, 2011 prescribed thereunder, (“Applicable Law”) and provides you with details about the manner in which your data is collected, stored and used by us. This Privacy Policy is intended to provide you with clear and complete information about your treatment of the personally identifiable data and information that Sonaac may collect in connection with the services offered by Sonaac and the way your personally identifiable information and data is stored and used by Sonaac. You are advised to read this Privacy Policy carefully, if you do not agree to the terms of the policy, please do not use or access Sonaac.</p>

					<p>Personally Identifiable Information means any information that relates to a natural person, which, either directly or indirectly, in combination with other information available or likely to be available with Sonaac, is capable of identifying such person. Therefore information such as your name, age, gender, date of birth, address, telephone/mobile number, e-mail ID, current location, and any other personal information that we collect, in combination with any other information about you, which is capable of identifying yourself, is known as personally identifiable information.</p>
					<p><strong> What this Privacy Policy Covers:</strong></p>
					<ul>
						<li>This Privacy Policy covers Sonaac’s treatment of your personally identifiable information that Sonaac may collect when you download Sonaac.</li>
						<li>This policy also covers Sonaac’s treatment of your personally identifiable information that Sonaac’s business partners share with Sonaac, which you may have disclosed to such business partners.</li>
						<li>This policy does not apply to companies or entities that Sonaac does not own or control, or has no contractual relationship with or to people that Sonaac does not employ, engage or manage.</li>
						<li>This Privacy Policy also covers information about the mobile/wireless device such as type of Mobile device, mobile device’s unique Device ID, The IP Address of your mobile Device, Operating Systems and the type of mobile internet browser (“Automatically Collected Information”) that you use to access the information, which is transmitted using Sonaac.</li>
					</ul>
					<p><strong> Information Collection and Use:</strong></p>
					<ul>
						<li>Sonaac may collect personally identifiable information when you download Sonaac. Sonaac may also receive personally identifiable information about yourself through its business partners, as stated above.</li>

						<li>When you download Sonaac; Sonaac may capture your full name, email address, mobile/telephone number, birth date, and technical information of your mobile device like type of mobile device, unique identification number of the mobile device, IP address of mobile device, operating system of the mobile internet browser, current location through GPS (or other Similar Technology) to determine your current location in order to determine the city where you are located within and display in location map for better serve .</li>

						<li>Sonaac also automatically receives and records information on Sonaac’s server logs from your browser on your mobile/wireless device including your IP address, Sonaac’s Cookie information and the mobile page you have requested to view.</li>
						<li>By signing up users is automatically eligible for receiving company's promotional offers through SMS, Email, Call, Pus, In-App notification etc. To unsubscribe users need to put a formal request on company support email at <strong>support@Sonaac.in </strong> .</li>
						<li>Sonaac uses the information collected by it to provide the services that you seek from Sonaac.</li>
					</ul>
					<p><strong> Information Sharing and Disclosure:</strong></p>
					<ul>
						<li>Sonaac will not sell or rent your personally identifiable information to anyone.</li>

						<li>Sonaac will divulge personally identifiable information about you to other companies or people or entities when:</li>

						<li>Sonaac has your specific written consent to share the information, which Sonaac will request from you, as and when the need arises;</li>

						<li>With its business partners to provide the services that you have requested from Sonaac;</li>

						<li>Sonaac needs to share the information with certain service partners in order to respond to your comments or to resolve service issues. (Unless Sonaac inform you differently, these partners have no independent right to use your information except to respond to your comments or to resolve service issues.);</li>

						<li>There are any requests from any Indian or foreign government, security agencies, law enforcement agencies, defence, revenue, regulatory or other authority, agency or officers;</li>

						<li>Sonaac will respond to any court summons, court orders or legal process; or</li>

						<li>Sonaac believes it is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, or as otherwise required by law.</li>

						<li>Sonaac may transfer information about you if Sonaac is acquired by or merged with another company. In this event, Sonaac will notify you before information about you is transferred and becomes subject to a different privacy policy.</li>
					</ul>
					<p><strong> Collection and Use of Non-Personal Information</strong></p>
						<p>We also collect data in a form that does not, on its own, permit direct association with any specific individual. We may collect, use, transfer, and disclose non-personal information for any purpose. The following are some examples of non-personal information that we collect and how we may use it:</p>
					<ul>
						<li>We may collect information such as occupation, language, zip code, area code, unique device identifier, referrer URL, location, so that we can better understand customer behaviour, do internal research on user’s demographics and improve our products, services, and advertising.</li>

						<li>We may collect and store details of how you use our services, including search queries. This information may be used to improve the relevancy of results provided by our services. Except in limited instances to ensure quality of our services over the Internet, such information will not be associated with your IP address.</li>
					</ul>					
					<p>If we do combine non-personal information with personally identifiable information the combined information will be treated as personally identifiable information for as long as it remains combined.</p>

					<p><strong> Cookies </strong></p>
					<ul>
						<li>Sonaac may set and access Sonaac Cookies on your mobile/wireless device.</li>
						<li>Sonaac shall allow other companies/entities that are presenting advertisements on Sonaac’s mobile pages or other publishers’ mobile to set and access their respective Cookies on your mobile device. Other companies' use of their cookies is subject to their own privacy policies, not this one. Advertisers or other companies do not have access to the Cookies of Sonaac.</li>
					</ul>

					<p><strong> Your Ability to Edit and Delete Your Account Information and Preferences </strong></p>
					<ul>
						<li>Sonaac gives you the ability to edit the information that is logged in when you download Sonaac, and preferences at any time, including whether you want Sonaac to contact you about offers etc and new updates Sonaac.</li>
					</ul>

					<p><strong> Security </strong></p>
					<ul>
						<li>In certain areas Sonaac uses industry-standard encryption to protect data transmissions.</li>
					</ul>

					<p><strong> Grievance Officer </strong></p>
					<p>In accordance with Information Technology Act, 2000 and Rule made thereunder, the name and contact details of Grievance Officer is provided below:</p>
					<strong>Sonaac Private Limited.</strong>
					<span>e-mail ID: - sonaacindia@gmail.com</span>

					<p><strong> Changes to this Privacy Policy </strong></p>
					<ul>
						<li>Sonaac may amend this privacy policy from time to time. If Sonaac makes any substantial changes in the way Sonaac uses your personally identifiable information Sonaac will notify you by posting a prominent announcement on Sonaac.</li>
					</ul>



					</div></div>