config/routes.rb
Rails.application.routes.draw do


root to: 'admin/admin_session#index'
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {
        sessions: 'api/v1/user/sessions',
        registrations: 'api/v1/user/registrations'
         }
      devise_for :drivers, controllers: {
        sessions: 'api/v1/driver/sessions',
        registrations: 'api/v1/driver/registrations'
         }
      resources :vehicles do
       collection do
        post :search_vehicle
        get :get_stations
        post :vehicle_details
       end
      end
      post '/get_drivers_near_to_me', to: 'commons#get_nearest_drivers'
      get '/check_user_existence/:email', to: 'commons#check_user'
      post '/offer_trip', to: 'commons#notify_cutomer_for_price'
      get '/get_drivers_offer/:user_id', to: 'commons#get_drivers_offer'
      get 'get_driver/:driver_id', to: 'commons#get_driver'
      post 'user_sign_out', to: 'commons#user_sign_out'
      post 'driver_sign_out', to: 'commons#driver_sign_out'
      post '/start_trip', to: 'commons#start_trip'
      get 'user_forgot_password/:user_id', to: 'commons#forgot_password'
      get 'driver_forgot_password/:driver_id', to: 'commons#driver_forgot_password'
      post 'get_nearest_user_driver', to: 'commons#get_nearest_user_driver'
      post 'cancel_trip', to: 'commons#cancel_trip'
      post 'stop_trip', to: 'commons#stop_trip'
      post 'resume_trip', to: 'commons#resume_trip'
      get '/get_state', to: 'state_city#get_state'
      get '/get_cities/:state', to: 'state_city#get_cities'

    end
  end
  namespace :admin do
    get '/', to: 'admin_session#index'
    post '/login', to: 'admin_session#login'
    get '/home', to: 'admin_session#home'
    delete '/session_destory', to: 'admin_session#destroy'
    get '/privacy_policy', to: 'admin_session#privacy_policy'
    resources :drivers, only: %i(edit index update)
    resources :vehicles do
      collection do
        post :vehicle_sheet
      end
    end
    resources :users, only: %i(edit index update destroy) 

  end

  #

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- <footer>
	<div class="footer">
	  <p>Posted by: Sahil Pruthi</p>
	  <p>Contact information: <a href="mailto:service@sonaac.com">service@sonaac.com</a>.</p>
	</div>
</footer> -->



<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <!-- <a class="navbar-brand" href="#">Sonaac</a> -->
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%=  link_to 'Sonaac', admin_home_path, class: "active navbar-brand"  if current_api_v1_user.present? %></li>
        <li><%=  link_to 'Sonaac', root_path, class: "active navbar-brand"  unless current_api_v1_user.present? %></li>
        <% if current_api_v1_user.present? %>
        <li><%= link_to 'Vehicle', admin_vehicles_path %></li>
        <li><%= link_to 'Users', admin_users_path%></li>
   			<li><%= link_to 'Drivers', admin_drivers_path%></li>
        <%end%>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout", admin_session_destory_path, :method => "DELETE" if current_api_v1_user.present?%></li>
        <li><%= link_to 'Login', root_path  unless current_api_v1_user.present? %> </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<script  src="http://code.jquery.com/jquery-3.3.1.js"  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <title>Api</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
	  	<%= render 'layouts/header' %> <%# if session[:admin].present? %>
	    <%= yield %>
	    <%= render 'layouts/footer' %>
	 </div>   
  </body>
</html>